version: '3.0'

services:

  jenkins:
    image: duckietown/dt-jenkins-ci:${ARCH}
    container_name: ${SITENAME}
    ports:
      - 8080:8080/tcp
    volumes:
      - ${JENKINS_HOME_LOCAL}:/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: ${SITENAME}

  https_proxy:
    image: duckietown/dt-jenkins-proxy:${ARCH}
    container_name: https_proxy_${SITENAME}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CERTFILE_LOCAL}:/var/www/ssl/certfile.pem
      - ${PRIVKEY_LOCAL}:/var/www/ssl/privkey.pem

